apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 5
  selector:
    word: coffee
  template:
    metadata:
      name: myrc
      labels:
        word: coffee
    spec:
      containers:
        - name: myrc
          image: nginx
          ports:
            - containerPort: 80
